
server:
  applicationContextPath: /
  adminContextPath: /
  applicationConnectors:
    - type: http
      # Replace with port number unique for this service
      port: 8081
  adminConnectors:
    - type: http
      # Replace with port number unique for this service
      port: 8082

database:
  driverClass: org.hsqldb.jdbcDriver
  url: jdbc:hsqldb:hsql://localhost:9001/dku-example-project
  logValidationErrors: true
  # See: https://stackoverflow.com/questions/10684244/dbcp-validationquery-for-different-databases
  validationQuery: SELECT * FROM INFORMATION_SCHEMA.SYSTEM_TABLES
  properties:
    hibernate.dialect: 'org.hibernate.dialect.HSQLDialect'
    hibernate.hbm2ddl.auto: update
#
# See https://www.dropwizard.io/en/latest/manual/configuration.html#logging
#
logging:
  level: INFO
  loggers:
    "nl.knaw.dans": TRACE
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601}] [%t] %c: %m%n%rEx"

    - type: file
      archive: false
      currentLogFilename: data/dku-example-project.log
